name: Auto deploy to splatoon.ca

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: "Auto deploy to splatoon.ca"
    runs-on: ubuntu-latest

    steps:
      - name: "Trigger deploy script over ssh"
        env:
            SSH_KEY: ${{ secrets.SSH_KEY }}
        run: ssh-agent bash -c "ssh-add <(echo '$SSH_KEY' | base64 -d) && ssh -o KnownHostsCommand='/usr/bin/env printf \"splatoon.ca ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILW/X4P6WLLfayBQMztBRFP2r/M7wAfJAOF4gNNcR7BV\"' splatoon@splatoon.ca"
